#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

"$basedir/../../../../../esbuild@0.28.1/node_modules/esbuild/bin/esbuild"   "$@"
exit $?
