FROM node:22-alpine

# Activar pnpm
RUN corepack enable && corepack prepare pnpm@9 --activate

WORKDIR /workspace/Frontend

# Conservamos tus configuraciones de red personalizadas para evitar timeouts
RUN pnpm config set fetch-retries 5 && \
    pnpm config set fetch-retry-mintimeout 20000 && \
    pnpm config set fetch-retry-maxtimeout 120000 && \
    pnpm config set network-timeout 100000

EXPOSE 3000

# El CMD final y el pnpm install se ejecutan desde el docker-compose.yml