FROM node:22-alpine

# Activar pnpm
RUN corepack enable && corepack prepare pnpm@9 --activate

WORKDIR /app

# Copiar manifiestos
COPY package.json pnpm-lock.yaml ./

RUN pnpm config set fetch-retries 5 && \
    pnpm config set fetch-retry-mintimeout 20000 && \
    pnpm config set fetch-retry-maxtimeout 120000 && \
    pnpm config set network-timeout 100000
# Instalar dependencias
RUN pnpm install

# Copiar el resto del código
COPY . .

EXPOSE 3000

CMD ["pnpm", "dev"]