FROM node:22-alpine

# Activar pnpm nativo
RUN corepack enable && corepack prepare pnpm@9 --activate

WORKDIR /app

# 1. Copiar manifiestos y lockfile para aprovechar la caché de Docker
COPY package.json pnpm-lock.yaml* ./

# 2. Instalación respetando estrictamente el lockfile (al no ser monorepo)
RUN pnpm install --frozen-lockfile

# 3. Copiar el resto del código fuente del Backend
COPY . .

EXPOSE 3001

CMD ["pnpm", "run", "dev"]