# Definición de la carpeta raíz del Backend
packages:
  - '.'

allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false

# Lista blanca oficial de pnpm v10+ para compilar binarios C++/Rust nativos
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - argon2
  - esbuild
  - prisma
