import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SessionWrapper from "./componets/session";
import "./globals.css";
import { IdleMonitor } from "./componets/timer_session";
import { DbProvider } from "./componets/tables_recharge";
import { auth } from "@/app/Login/types/auth"; // 👈 IMPORTANTE: Importa tu función auth de NextAuth v5

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Convertimos el RootLayout en una función asíncrona para leer la sesión en el servidor
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  // 🚀 Traemos la sesión directamente desde las cookies del servidor en tiempo de renderizado
  const session = await auth(); 

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* 🎯 Le inyectamos la sesión directo al Wrapper */}
        <SessionWrapper session={session}> 
          <DbProvider>
            {children}
            <IdleMonitor />
          </DbProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}