/*
  Warnings:

  - The primary key for the `audit_logs` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The `ID_AUDIT` column on the `audit_logs` table would be dropped and recreated. This will lead to data loss if there is data in the column.
  - You are about to drop the column `CREATED_AT` on the `tarifas` table. All the data in the column will be lost.
  - You are about to drop the column `PRECIO_MINIMO` on the `tarifas` table. All the data in the column will be lost.

*/
-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "vector";

-- CreateEnum
CREATE TYPE "FrecuenciaEjecucion" AS ENUM ('UNA_VEZ', 'DIARIA', 'SEMANAL', 'PROGRAMADA_CRON');

-- CreateEnum
CREATE TYPE "statuscliente" AS ENUM ('ACTIVO', 'INACTIVO');

-- CreateEnum
CREATE TYPE "tipocliente" AS ENUM ('NATURAL', 'JURIDICO');

-- CreateEnum
CREATE TYPE "Estados" AS ENUM ('VENCIDA', 'RECHAZADA', 'APROBADO', 'BORRADOR', 'PENDIENTE_CONSOLIDAR', 'PENDIENTE_APROBAR', 'FINALIZADA');

-- CreateEnum
CREATE TYPE "ProveedorAlmacenamiento" AS ENUM ('LOCAL', 'AWS_S3', 'GOOGLE_DRIVE');

-- AlterTable
ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_pkey",
DROP COLUMN "ID_AUDIT",
ADD COLUMN     "ID_AUDIT" SERIAL NOT NULL,
ADD CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("ID_AUDIT");

-- AlterTable
ALTER TABLE "tarifas" DROP COLUMN "CREATED_AT",
DROP COLUMN "PRECIO_MINIMO",
ADD COLUMN     "Instrumento" TEXT NOT NULL DEFAULT 'n/a',
ADD COLUMN     "Norma" TEXT NOT NULL DEFAULT 'n/a',
ALTER COLUMN "ESTADO" SET DEFAULT 'ACTIVO';

-- AlterTable
ALTER TABLE "usuarios" ADD COLUMN     "elminado" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "intentos" INTEGER NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE "notificaciones" (
    "ID_NOTIFICACION" SERIAL NOT NULL,
    "ID_USUARIO_FK" INTEGER NOT NULL,
    "MENSAJE" TEXT NOT NULL,
    "MODULO" TEXT NOT NULL,
    "VISTO" BOOLEAN NOT NULL DEFAULT false,
    "NIVEL_PRIORIDAD" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notificaciones_pkey" PRIMARY KEY ("ID_NOTIFICACION")
);

-- CreateTable
CREATE TABLE "historial_tarifas" (
    "ID_HISTORIAL" SERIAL NOT NULL,
    "ID_TARIFA_FK" INTEGER NOT NULL,
    "FECHA_INICIO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FECHA_FIN" TIMESTAMP(3),
    "PRECIO_U" DECIMAL(12,2) NOT NULL,

    CONSTRAINT "historial_tarifas_pkey" PRIMARY KEY ("ID_HISTORIAL")
);

-- CreateTable
CREATE TABLE "parametros_sistema" (
    "ID_PARAMETRO" SERIAL NOT NULL,
    "CLAVE" TEXT NOT NULL,
    "CODIGO_SCRIPT" TEXT,
    "FRECUENCIA" "FrecuenciaEjecucion" NOT NULL DEFAULT 'UNA_VEZ',
    "EXPRESION_CRON" TEXT,
    "PROXIMA_EJECUCION" TIMESTAMP(3),
    "ULTIMA_EJECUCION" TIMESTAMP(3),

    CONSTRAINT "parametros_sistema_pkey" PRIMARY KEY ("ID_PARAMETRO")
);

-- CreateTable
CREATE TABLE "plantillas" (
    "ID_PLANTILLA" SERIAL NOT NULL,
    "MODULO" TEXT NOT NULL DEFAULT 'COTIZACIONES',
    "ACTIVA" BOOLEAN NOT NULL DEFAULT true,
    "NOMBRE" TEXT NOT NULL,

    CONSTRAINT "plantillas_pkey" PRIMARY KEY ("ID_PLANTILLA")
);

-- CreateTable
CREATE TABLE "clientes" (
    "ID_CLIENTE" SERIAL NOT NULL,
    "NIT" TEXT NOT NULL,
    "RAZON_SOCIAL" TEXT NOT NULL,
    "CORREO" TEXT NOT NULL,
    "NOMBRE_CONTACTO" TEXT,
    "TELEFONO" TEXT,
    "OBSERVACION" TEXT,
    "ID_RUT_DOCUMENTO_FK" INTEGER,
    "status" "statuscliente" NOT NULL DEFAULT 'ACTIVO',
    "createat" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dirrecion" TEXT NOT NULL DEFAULT 'n/a',
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ciudad" TEXT DEFAULT 'Cali',
    "TIPO_CLIENTE" "tipocliente" NOT NULL DEFAULT 'NATURAL',

    CONSTRAINT "clientes_pkey" PRIMARY KEY ("ID_CLIENTE")
);

-- CreateTable
CREATE TABLE "cotizaciones" (
    "ID_COTIZACION" SERIAL NOT NULL,
    "CODIGO_COTIZACION" TEXT NOT NULL,
    "ID_CLIENTE_FK" INTEGER,
    "MONTO_TOTAL" DECIMAL(12,2),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3),
    "viaticos" DECIMAL(12,2) DEFAULT 0,
    "PROX_END_DATE" TIMESTAMP(3),
    "ESTADO" "Estados" NOT NULL DEFAULT 'BORRADOR',
    "descuento" INTEGER DEFAULT 0,

    CONSTRAINT "cotizaciones_pkey" PRIMARY KEY ("ID_COTIZACION")
);

-- CreateTable
CREATE TABLE "cotizacion_detalles" (
    "ID_DETALLE" SERIAL NOT NULL,
    "ID_COTIZACION_FK" INTEGER NOT NULL,
    "EQUIPO_DESCRIPCION" TEXT NOT NULL,
    "TIPO_SERVICIO" TEXT NOT NULL,
    "MAGNITUD" TEXT NOT NULL,
    "NORMA_TECNICA" TEXT,
    "CANTIDAD" INTEGER NOT NULL,
    "VALOR_UNITARIO" DECIMAL(12,2) NOT NULL,
    "VALOR_TOTAL" DECIMAL(12,2) NOT NULL,
    "sitio" TEXT,

    CONSTRAINT "cotizacion_detalles_pkey" PRIMARY KEY ("ID_DETALLE")
);

-- CreateTable
CREATE TABLE "ordenes_trabajo" (
    "ID_ORDEN_TRABAJO" SERIAL NOT NULL,
    "CODIGO_OT" TEXT NOT NULL,
    "ID_COTIZACION_FK" INTEGER,
    "ID_CLIENTE_FK" INTEGER,
    "CORREO_CERTIFICADO" TEXT,
    "CORREO_FACTURA" TEXT,
    "FECHA_LIMITE_FACTURACION" TIMESTAMP(3),
    "ES_INTERNO_USC" BOOLEAN NOT NULL DEFAULT false,
    "ES_EN_SITIO" BOOLEAN NOT NULL DEFAULT false,
    "ES_LAB_PERMANENTE" BOOLEAN NOT NULL DEFAULT true,
    "PERSONA_CONTACTO" TEXT,
    "TELEFONO_CONTACTO" TEXT,
    "FECHA_CALIBRACION" TIMESTAMP(3),
    "RESPONSABLE" TEXT,
    "OBSERVACIONES" TEXT,
    "REQUIERE_ANEXO" BOOLEAN NOT NULL DEFAULT false,
    "ESTADO" TEXT NOT NULL DEFAULT 'EN_PROCESO',
    "ESTADO_REVISION" TEXT NOT NULL DEFAULT 'PENDIENTE_REVISION',
    "MOTIVO_RECHAZO" TEXT,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ordenes_trabajo_pkey" PRIMARY KEY ("ID_ORDEN_TRABAJO")
);

-- CreateTable
CREATE TABLE "orden_trabajo_detalles" (
    "ID_DETALLE" SERIAL NOT NULL,
    "ID_ORDEN_TRABAJO_FK" INTEGER NOT NULL,
    "ITEM" INTEGER NOT NULL,
    "TIPO_SERVICIO" TEXT NOT NULL,
    "INSTRUMENTO" TEXT NOT NULL,
    "FABRICANTE" TEXT,
    "MODELO" TEXT,
    "SERIE" TEXT,
    "CODIGO_INVENTARIO" TEXT,
    "UBICACION" TEXT,
    "PUNTOS_CALIBRAR" TEXT[],
    "UNIDAD" TEXT,
    "INTERVALO_RANGO" TEXT,
    "RESOLUCION" TEXT,
    "asignado" INTEGER NOT NULL,
    "DECLARACION_CONFORMIDAD" BOOLEAN NOT NULL DEFAULT false,
    "LIMITE_CONTROL_EMC" TEXT,
    "DOC_ESPECIFICACION" TEXT,
    "REGLA_DECISION" TEXT,

    CONSTRAINT "orden_trabajo_detalles_pkey" PRIMARY KEY ("ID_DETALLE")
);

-- CreateTable
CREATE TABLE "recepciones_equipo" (
    "ID_RECEPCION" SERIAL NOT NULL,
    "CODIGO_RECEPCION" TEXT NOT NULL,
    "ID_COTIZACION_FK" INTEGER,
    "ID_ORDEN_TRABAJO_FK" INTEGER,
    "SOLICITANTE" TEXT NOT NULL,
    "NOMBRE_ENTREGA" TEXT,
    "SITIO_CALIBRACION" TEXT NOT NULL,
    "FECHA_RECEPCION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FECHA_SALIDA" TIMESTAMP(3),
    "NOMBRE_RECIBE" TEXT,
    "NOMBRE_EMPACA" TEXT,
    "NOMBRE_CALIBRA" TEXT,
    "NOMBRE_RECIBE_SERVICIO" TEXT,
    "ACCESORIOS" TEXT,
    "PRUEBAS_COMPLETAS" BOOLEAN NOT NULL DEFAULT true,
    "OBSERVACIONES_PRUEBAS" TEXT,
    "ESTADO" TEXT NOT NULL DEFAULT 'RECIBIDO',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "recepciones_equipo_pkey" PRIMARY KEY ("ID_RECEPCION")
);

-- CreateTable
CREATE TABLE "recepcion_equipo_detalles" (
    "ID_INSTRUMENTO" SERIAL NOT NULL,
    "ID_RECEPCION_FK" INTEGER NOT NULL,
    "INSTRUMENTO" TEXT NOT NULL,
    "MARCA" TEXT,
    "MODELO" TEXT,
    "SERIE" TEXT,
    "CODIGO_INVENTARIO" TEXT,
    "RESOLUCION" TEXT,
    "TIPO_SENSOR_TEMP" TEXT,
    "ESTADO_IBC" JSONB,
    "ESTAMPILLA" TEXT,
    "OBSERVACIONES" TEXT,

    CONSTRAINT "recepcion_equipo_detalles_pkey" PRIMARY KEY ("ID_INSTRUMENTO")
);

-- CreateTable
CREATE TABLE "calibraciones" (
    "ID_CALIBRACION" SERIAL NOT NULL,
    "ID_INSTRUMENTO_FK" INTEGER NOT NULL,
    "ID_TECNICO_FK" INTEGER NOT NULL,
    "DATOS_TECNICOS_JSON" JSONB NOT NULL,
    "OBSERVACIONES" TEXT,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "calibraciones_pkey" PRIMARY KEY ("ID_CALIBRACION")
);

-- CreateTable
CREATE TABLE "certificados" (
    "ID_CERTIFICADO" SERIAL NOT NULL,
    "CODIGO_CERTIFICADO" TEXT NOT NULL,
    "ID_CALIBRACION_FK" INTEGER NOT NULL,
    "ID_DOCUMENTO_FK" INTEGER NOT NULL,

    CONSTRAINT "certificados_pkey" PRIMARY KEY ("ID_CERTIFICADO")
);

-- CreateTable
CREATE TABLE "documentos" (
    "ID_DOCUMENTO" SERIAL NOT NULL,
    "NOMBRE" TEXT NOT NULL,
    "RUTA_URL" TEXT NOT NULL,
    "PROVEEDOR" "ProveedorAlmacenamiento" NOT NULL DEFAULT 'LOCAL',
    "MIME_TYPE" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_COTIZACION_FK" INTEGER,
    "ID_ORDEN_TRABAJO_FK" INTEGER,
    "ID_RECEPCION_FK" INTEGER,
    "ID_PLANTILLA_FK" INTEGER,

    CONSTRAINT "documentos_pkey" PRIMARY KEY ("ID_DOCUMENTO")
);

-- CreateTable
CREATE TABLE "version_plantillas" (
    "ID_VERSION_PLANTILLA" SERIAL NOT NULL,
    "ID_PLANTILLA_FK" INTEGER NOT NULL,
    "VERSION" INTEGER NOT NULL DEFAULT 1,
    "MAPEO_EXCEL_JSON" JSONB,
    "ID_USUARIO_CREADOR_FK" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_DOCUMENTOS_FK" INTEGER,

    CONSTRAINT "version_plantillas_pkey" PRIMARY KEY ("ID_VERSION_PLANTILLA")
);

-- CreateTable
CREATE TABLE "version_documentos" (
    "ID_VERSION" SERIAL NOT NULL,
    "ID_DOCUMENTO_FK" INTEGER NOT NULL,
    "VERSION" INTEGER NOT NULL DEFAULT 1,
    "RUTA_URL" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "usuario_fk" INTEGER NOT NULL,
    "content_json" JSONB,

    CONSTRAINT "version_documentos_pkey" PRIMARY KEY ("ID_VERSION")
);

-- CreateTable
CREATE TABLE "document_chunks" (
    "ID_CHUNK" SERIAL NOT NULL,
    "ID_DOCUMENTO_FK" INTEGER NOT NULL,
    "CONTENIDO" TEXT NOT NULL,
    "embedding" vector,

    CONSTRAINT "document_chunks_pkey" PRIMARY KEY ("ID_CHUNK")
);

-- CreateTable
CREATE TABLE "sellos" (
    "ID_SELLO" SERIAL NOT NULL,
    "NOMBRE" TEXT NOT NULL,
    "ID_DOCUMENTO_FK" INTEGER NOT NULL,
    "ESTADO" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "sellos_pkey" PRIMARY KEY ("ID_SELLO")
);

-- CreateTable
CREATE TABLE "certificado_sellos" (
    "ID_CERTIFICADO_FK" INTEGER NOT NULL,
    "ID_SELLO_FK" INTEGER NOT NULL,

    CONSTRAINT "certificado_sellos_pkey" PRIMARY KEY ("ID_CERTIFICADO_FK","ID_SELLO_FK")
);

-- CreateIndex
CREATE INDEX "historial_tarifas_ID_TARIFA_FK_FECHA_INICIO_FECHA_FIN_idx" ON "historial_tarifas"("ID_TARIFA_FK", "FECHA_INICIO", "FECHA_FIN");

-- CreateIndex
CREATE UNIQUE INDEX "parametros_sistema_CLAVE_key" ON "parametros_sistema"("CLAVE");

-- CreateIndex
CREATE INDEX "parametros_sistema_PROXIMA_EJECUCION_idx" ON "parametros_sistema"("PROXIMA_EJECUCION");

-- CreateIndex
CREATE UNIQUE INDEX "clientes_NIT_key" ON "clientes"("NIT");

-- CreateIndex
CREATE UNIQUE INDEX "clientes_ID_RUT_DOCUMENTO_FK_key" ON "clientes"("ID_RUT_DOCUMENTO_FK");

-- CreateIndex
CREATE UNIQUE INDEX "cotizaciones_CODIGO_COTIZACION_key" ON "cotizaciones"("CODIGO_COTIZACION");

-- CreateIndex
CREATE INDEX "cotizaciones_CREATED_AT_idx" ON "cotizaciones"("CREATED_AT");

-- CreateIndex
CREATE UNIQUE INDEX "ordenes_trabajo_CODIGO_OT_key" ON "ordenes_trabajo"("CODIGO_OT");

-- CreateIndex
CREATE INDEX "ordenes_trabajo_CODIGO_OT_idx" ON "ordenes_trabajo"("CODIGO_OT");

-- CreateIndex
CREATE INDEX "ordenes_trabajo_FECHA_CALIBRACION_idx" ON "ordenes_trabajo"("FECHA_CALIBRACION");

-- CreateIndex
CREATE UNIQUE INDEX "recepciones_equipo_CODIGO_RECEPCION_key" ON "recepciones_equipo"("CODIGO_RECEPCION");

-- CreateIndex
CREATE INDEX "recepciones_equipo_CREATED_AT_idx" ON "recepciones_equipo"("CREATED_AT");

-- CreateIndex
CREATE UNIQUE INDEX "calibraciones_ID_INSTRUMENTO_FK_key" ON "calibraciones"("ID_INSTRUMENTO_FK");

-- CreateIndex
CREATE UNIQUE INDEX "certificados_CODIGO_CERTIFICADO_key" ON "certificados"("CODIGO_CERTIFICADO");

-- CreateIndex
CREATE UNIQUE INDEX "certificados_ID_CALIBRACION_FK_key" ON "certificados"("ID_CALIBRACION_FK");

-- CreateIndex
CREATE INDEX "documentos_ID_COTIZACION_FK_idx" ON "documentos"("ID_COTIZACION_FK");

-- CreateIndex
CREATE INDEX "documentos_ID_ORDEN_TRABAJO_FK_idx" ON "documentos"("ID_ORDEN_TRABAJO_FK");

-- CreateIndex
CREATE INDEX "documentos_ID_RECEPCION_FK_idx" ON "documentos"("ID_RECEPCION_FK");

-- CreateIndex
CREATE INDEX "documentos_ID_PLANTILLA_FK_idx" ON "documentos"("ID_PLANTILLA_FK");

-- AddForeignKey
ALTER TABLE "notificaciones" ADD CONSTRAINT "notificaciones_ID_USUARIO_FK_fkey" FOREIGN KEY ("ID_USUARIO_FK") REFERENCES "usuarios"("ID_USUARIO_AUTO_INCREMENT") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "historial_tarifas" ADD CONSTRAINT "historial_tarifas_ID_TARIFA_FK_fkey" FOREIGN KEY ("ID_TARIFA_FK") REFERENCES "tarifas"("ID_TARIFA") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "clientes" ADD CONSTRAINT "clientes_ID_RUT_DOCUMENTO_FK_fkey" FOREIGN KEY ("ID_RUT_DOCUMENTO_FK") REFERENCES "documentos"("ID_DOCUMENTO") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "cotizaciones" ADD CONSTRAINT "cotizaciones_ID_CLIENTE_FK_fkey" FOREIGN KEY ("ID_CLIENTE_FK") REFERENCES "clientes"("ID_CLIENTE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "cotizacion_detalles" ADD CONSTRAINT "cotizacion_detalles_ID_COTIZACION_FK_fkey" FOREIGN KEY ("ID_COTIZACION_FK") REFERENCES "cotizaciones"("ID_COTIZACION") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ordenes_trabajo" ADD CONSTRAINT "ordenes_trabajo_ID_CLIENTE_FK_fkey" FOREIGN KEY ("ID_CLIENTE_FK") REFERENCES "clientes"("ID_CLIENTE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ordenes_trabajo" ADD CONSTRAINT "ordenes_trabajo_ID_COTIZACION_FK_fkey" FOREIGN KEY ("ID_COTIZACION_FK") REFERENCES "cotizaciones"("ID_COTIZACION") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "orden_trabajo_detalles" ADD CONSTRAINT "orden_trabajo_detalles_asignado_fkey" FOREIGN KEY ("asignado") REFERENCES "usuarios"("ID_USUARIO_AUTO_INCREMENT") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "orden_trabajo_detalles" ADD CONSTRAINT "orden_trabajo_detalles_ID_ORDEN_TRABAJO_FK_fkey" FOREIGN KEY ("ID_ORDEN_TRABAJO_FK") REFERENCES "ordenes_trabajo"("ID_ORDEN_TRABAJO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "recepciones_equipo" ADD CONSTRAINT "recepciones_equipo_ID_COTIZACION_FK_fkey" FOREIGN KEY ("ID_COTIZACION_FK") REFERENCES "cotizaciones"("ID_COTIZACION") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "recepciones_equipo" ADD CONSTRAINT "recepciones_equipo_ID_ORDEN_TRABAJO_FK_fkey" FOREIGN KEY ("ID_ORDEN_TRABAJO_FK") REFERENCES "ordenes_trabajo"("ID_ORDEN_TRABAJO") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "recepcion_equipo_detalles" ADD CONSTRAINT "recepcion_equipo_detalles_ID_RECEPCION_FK_fkey" FOREIGN KEY ("ID_RECEPCION_FK") REFERENCES "recepciones_equipo"("ID_RECEPCION") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "calibraciones" ADD CONSTRAINT "calibraciones_ID_INSTRUMENTO_FK_fkey" FOREIGN KEY ("ID_INSTRUMENTO_FK") REFERENCES "recepcion_equipo_detalles"("ID_INSTRUMENTO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "calibraciones" ADD CONSTRAINT "calibraciones_ID_TECNICO_FK_fkey" FOREIGN KEY ("ID_TECNICO_FK") REFERENCES "usuarios"("ID_USUARIO_AUTO_INCREMENT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "certificados" ADD CONSTRAINT "certificados_ID_CALIBRACION_FK_fkey" FOREIGN KEY ("ID_CALIBRACION_FK") REFERENCES "calibraciones"("ID_CALIBRACION") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "certificados" ADD CONSTRAINT "certificados_ID_DOCUMENTO_FK_fkey" FOREIGN KEY ("ID_DOCUMENTO_FK") REFERENCES "documentos"("ID_DOCUMENTO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "documentos" ADD CONSTRAINT "documentos_ID_COTIZACION_FK_fkey" FOREIGN KEY ("ID_COTIZACION_FK") REFERENCES "cotizaciones"("ID_COTIZACION") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "documentos" ADD CONSTRAINT "documentos_ID_ORDEN_TRABAJO_FK_fkey" FOREIGN KEY ("ID_ORDEN_TRABAJO_FK") REFERENCES "ordenes_trabajo"("ID_ORDEN_TRABAJO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "documentos" ADD CONSTRAINT "documentos_ID_RECEPCION_FK_fkey" FOREIGN KEY ("ID_RECEPCION_FK") REFERENCES "recepciones_equipo"("ID_RECEPCION") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "version_plantillas" ADD CONSTRAINT "version_plantillas_ID_DOCUMENTOS_FK_fkey" FOREIGN KEY ("ID_DOCUMENTOS_FK") REFERENCES "documentos"("ID_DOCUMENTO") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "version_plantillas" ADD CONSTRAINT "version_plantillas_ID_PLANTILLA_FK_fkey" FOREIGN KEY ("ID_PLANTILLA_FK") REFERENCES "plantillas"("ID_PLANTILLA") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "version_plantillas" ADD CONSTRAINT "version_plantillas_ID_USUARIO_CREADOR_FK_fkey" FOREIGN KEY ("ID_USUARIO_CREADOR_FK") REFERENCES "usuarios"("ID_USUARIO_AUTO_INCREMENT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "version_documentos" ADD CONSTRAINT "version_documentos_ID_DOCUMENTO_FK_fkey" FOREIGN KEY ("ID_DOCUMENTO_FK") REFERENCES "documentos"("ID_DOCUMENTO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "version_documentos" ADD CONSTRAINT "version_documentos_usuario_fk_fkey" FOREIGN KEY ("usuario_fk") REFERENCES "usuarios"("ID_USUARIO_AUTO_INCREMENT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "document_chunks" ADD CONSTRAINT "document_chunks_ID_DOCUMENTO_FK_fkey" FOREIGN KEY ("ID_DOCUMENTO_FK") REFERENCES "documentos"("ID_DOCUMENTO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sellos" ADD CONSTRAINT "sellos_ID_DOCUMENTO_FK_fkey" FOREIGN KEY ("ID_DOCUMENTO_FK") REFERENCES "documentos"("ID_DOCUMENTO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "certificado_sellos" ADD CONSTRAINT "certificado_sellos_ID_CERTIFICADO_FK_fkey" FOREIGN KEY ("ID_CERTIFICADO_FK") REFERENCES "certificados"("ID_CERTIFICADO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "certificado_sellos" ADD CONSTRAINT "certificado_sellos_ID_SELLO_FK_fkey" FOREIGN KEY ("ID_SELLO_FK") REFERENCES "sellos"("ID_SELLO") ON DELETE RESTRICT ON UPDATE CASCADE;
