-- CreateEnum
CREATE TYPE "Estado" AS ENUM ('ACTIVO', 'INACTIVO', 'SUSPENDIDO');

-- CreateTable
CREATE TABLE "usuarios" (
    "ID_USUARIO_AUTO_INCREMENT" SERIAL NOT NULL,
    "NOMBRE_COMPLETO" TEXT NOT NULL,
    "contraseña" TEXT NOT NULL,
    "ESTADO" "Estado" NOT NULL,
    "ID_ROL_FK" INTEGER NOT NULL,
    "CORREO_INSTITUCION" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_AT" TIMESTAMP(3),

    CONSTRAINT "usuarios_pkey" PRIMARY KEY ("ID_USUARIO_AUTO_INCREMENT")
);

-- CreateTable
CREATE TABLE "roles" (
    "ID_ROL_INCREMENT" SERIAL NOT NULL,
    "NOMBRE_ROL" TEXT NOT NULL,
    "PERMISOS_JSON" JSONB NOT NULL,
    "JUSTIFICACION" TEXT NOT NULL,
    "DIRECTRIZ_DIRECTOR" BOOLEAN NOT NULL,

    CONSTRAINT "roles_pkey" PRIMARY KEY ("ID_ROL_INCREMENT")
);

-- CreateTable
CREATE TABLE "tarifas" (
    "ID_TARIFA" SERIAL NOT NULL,
    "MAGNITUD" TEXT NOT NULL,
    "TIPO_SERVICIO" TEXT NOT NULL,
    "PRECIO_MINIMO" DOUBLE PRECISION NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ESTADO" TEXT NOT NULL,

    CONSTRAINT "tarifas_pkey" PRIMARY KEY ("ID_TARIFA")
);

-- CreateTable
CREATE TABLE "audit_logs" (
    "id" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "tableName" TEXT NOT NULL,
    "recordId" TEXT NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "details" JSONB NOT NULL,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "usuarios_CORREO_INSTITUCION_key" ON "usuarios"("CORREO_INSTITUCION");

-- AddForeignKey
ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_ID_ROL_FK_fkey" FOREIGN KEY ("ID_ROL_FK") REFERENCES "roles"("ID_ROL_INCREMENT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "usuarios"("ID_USUARIO_AUTO_INCREMENT") ON DELETE RESTRICT ON UPDATE CASCADE;
